/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.TelaJogo;

import Logica.Robo;
import javax.swing.JOptionPane;

/**
 *
 * @author vinan
 */

public class manualTelaJogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manualTelaJogo.class.getName());
    
    // ---- 1. ATRIBUTOS ----
    private Robo meuRobo;
    private int xAlimento = 0; // Exemplo: alimento em (3, 2)
    private int yAlimento = 0;
    
    private void resetarParaInicio() {
        // 1. Mostra a tela de configuração e limpa os campos
        telaPosicaoAlimento.setVisible(true);
        posicaoXField.setText(""); // Limpa o campo X
        posicaoYField.setText(""); // Limpa o campo Y
        
        // 2. Oculta e desabilita os botões de movimento
        jButton1.setEnabled(false);
        jButton1.setVisible(false);
        
        jButton2.setEnabled(false);
        jButton2.setVisible(false);
        
        jButton3.setEnabled(false);
        jButton3.setVisible(false);
        
        jButton4.setEnabled(false);
        jButton4.setVisible(false);
        
        // 3. Oculta o painel do jogo
        painelDoJogo.setVisible(false);
    }
    
    private void atualizarAposMovimento() {
        // 1. Atualiza o painel com os novos dados
        TabuleiroPanel meuPainel = (TabuleiroPanel) painelDoJogo;
        meuPainel.atualizarEstado(meuRobo, xAlimento, yAlimento);

        // 2. Manda redesenhar!
        painelDoJogo.repaint();

        // 3. CHECAGEM DE VITÓRIA
        if (meuRobo.encontrouAlimento(xAlimento, yAlimento)) {

            // 3a. Mostrar a mensagem de vitória
            // 'this' faz a mensagem aparecer centralizada na sua janela
            JOptionPane.showMessageDialog(this, 
                    "Parabéns! Você encontrou o alimento!", 
                    "Vitória!", 
                    JOptionPane.INFORMATION_MESSAGE);

            // 3b. Parar o jogo (desabilitar os botões)
            jButton1.setEnabled(false); // Botão "Up"
            jButton2.setEnabled(false); // Botão "Left"
            jButton3.setEnabled(false); // Botão "Down"
            jButton4.setEnabled(false); // Botão "Right"
            
            // 3c. Perguntar se quer jogar novamente
            Object[] options = {"Jogar Novamente", "Sair"};
            int escolha = JOptionPane.showOptionDialog(this,
                "Deseja jogar novamente?",
                "Fim de Jogo",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,     // sem ícone customizado
                options,  // os botões que definimos
                options[0]); // botão padrão
            
            if (escolha == 0) { // 0 é o primeiro botão: "Jogar Novamente"
                // Reseta o jogo para a tela de input
                resetarParaInicio(); 
            } else {
                // Se for 1 ("Sair") ou se o usuário fechar a janela
                System.exit(0); // Fecha a aplicação
            }
        }
    }
    
    public manualTelaJogo() {
        initComponents();
        
        // Oculta e desabilitar os botões para andar e o painel
        resetarParaInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDoJogo = new Interface.TelaJogo.TabuleiroPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        telaPosicaoAlimento = new javax.swing.JPanel();
        posicaoXField = new javax.swing.JTextField();
        jLabelX = new javax.swing.JLabel();
        posicaoYField = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Robo Logo");

        painelDoJogo.setBackground(new java.awt.Color(255, 255, 255));
        painelDoJogo.setName("painelDoJogo"); // NOI18N
        painelDoJogo.setPreferredSize(new java.awt.Dimension(572, 450));

        javax.swing.GroupLayout painelDoJogoLayout = new javax.swing.GroupLayout(painelDoJogo);
        painelDoJogo.setLayout(painelDoJogoLayout);
        painelDoJogoLayout.setHorizontalGroup(
            painelDoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        painelDoJogoLayout.setVerticalGroup(
            painelDoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jButton1.setText("Up");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 65));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Left");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 65));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Down");
        jButton3.setPreferredSize(new java.awt.Dimension(80, 65));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Right");
        jButton4.setPreferredSize(new java.awt.Dimension(80, 65));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        telaPosicaoAlimento.setForeground(new java.awt.Color(30, 30, 30));

        posicaoXField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoXFieldActionPerformed(evt);
            }
        });

        jLabelX.setText("Posição X (0-3)");

        jLabelY.setText("Posição Y (0-3)");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setText("Qual é a posição da fruta?");

        javax.swing.GroupLayout telaPosicaoAlimentoLayout = new javax.swing.GroupLayout(telaPosicaoAlimento);
        telaPosicaoAlimento.setLayout(telaPosicaoAlimentoLayout);
        telaPosicaoAlimentoLayout.setHorizontalGroup(
            telaPosicaoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPosicaoAlimentoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaPosicaoAlimentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(telaPosicaoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posicaoYField)
                    .addGroup(telaPosicaoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelX)
                        .addComponent(posicaoXField)))
                .addGap(141, 141, 141))
        );
        telaPosicaoAlimentoLayout.setVerticalGroup(
            telaPosicaoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPosicaoAlimentoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabelX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posicaoXField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelY)
                .addGap(18, 18, 18)
                .addComponent(posicaoYField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(painelDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(telaPosicaoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(telaPosicaoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            meuRobo.mover("up");
        } catch (excecao.MovimentoInvalidoException e) {
            System.out.println(e.getMessage());
            return;
        }

        // Manda redesenhar!
        atualizarAposMovimento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            meuRobo.mover("down");
        } catch (excecao.MovimentoInvalidoException e) {
            System.out.println(e.getMessage());
            return;
        }
        
        atualizarAposMovimento();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            meuRobo.mover("left");
        } catch (excecao.MovimentoInvalidoException e) {
            System.out.println(e.getMessage());
            return;
        }
        
        atualizarAposMovimento();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            meuRobo.mover("right");
        } catch (excecao.MovimentoInvalidoException e) {
            System.out.println(e.getMessage());
            return;
        }
        
        atualizarAposMovimento();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void posicaoXFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoXFieldActionPerformed

    }//GEN-LAST:event_posicaoXFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int xAlimentoAtual = Integer.parseInt(posicaoXField.getText());
            int yAlimentoAtual = Integer.parseInt(posicaoYField.getText());
            
            if (xAlimentoAtual == 0 && yAlimentoAtual == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Posição inválida. Digite valores diferentes da origem (0,0)", 
                    "Erro de Posição", 
                    JOptionPane.ERROR_MESSAGE);
            } else if (xAlimentoAtual < 0 || xAlimentoAtual > 3 || yAlimentoAtual < 0 || yAlimentoAtual > 3) {
                JOptionPane.showMessageDialog(this, 
                    "Posição inválida. Digite valores entre 0 e 3.", 
                    "Erro de Posição", 
                    JOptionPane.ERROR_MESSAGE);
            } else {
                this.xAlimento = xAlimentoAtual;
                this.yAlimento = yAlimentoAtual;
                
                meuRobo = new Robo("Azul");
                
                telaPosicaoAlimento.setVisible(false);
                
                jButton1.setEnabled(true);
                jButton1.setVisible(true);

                jButton2.setEnabled(true);
                jButton2.setVisible(true);

                jButton3.setEnabled(true);
                jButton3.setVisible(true);

                jButton4.setEnabled(true);
                jButton4.setVisible(true);

                painelDoJogo.setVisible(true);
                
                atualizarAposMovimento();
            }
        } catch (NumberFormatException e) {
        // Se o usuário não digitou um número
            JOptionPane.showMessageDialog(this, 
                "Por favor, digite apenas números válidos.", 
                "Erro de Formato", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Outro erro inesperado
            JOptionPane.showMessageDialog(this, 
                "Ocorreu um erro: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new manualTelaJogo().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel painelDoJogo;
    private javax.swing.JTextField posicaoXField;
    private javax.swing.JTextField posicaoYField;
    private javax.swing.JPanel telaPosicaoAlimento;
    // End of variables declaration//GEN-END:variables
}